version: "3"

services:
  game:
    build: .
    volumes:
      - ./Server/lib:/app/Server/lib/
    depends_on:
      - db
    command: yarn prod:game
    restart: always
    ports:
      # 일단 복구
      - "8469:8469"
      # 0번 게임 서버 메인 포트 (+0)
      - "2929:2929"
      # 0번 게임 서버 워커 포트 (+416 ~)
      - "3345:3345"
      - "3346:3346"
      - "3347:3347"
      - "3348:3348"
  web:
    build: .
    volumes:
      - ./Server/lib:/app/Server/lib/
      - kkutu_data:/kkutu
    command: yarn prod:web
    restart: always
    depends_on:
      - db
      - game
    ports:
      - "2930:80"
  db:
    build:
      context: .
      dockerfile: ./psql.Dockerfile
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis
    volumes:
      - ./data/redis:/data
    ports:
      - "127.0.0.1:6379:6379"

volumes:
  kkutu_data:
  db_data:
